'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Login

    '''<summary>
    '''txtRegEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvRegEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRegEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revRegEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revRegEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtRegPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvRegPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRegPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revRegPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revRegPassword As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btnSubmitReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitReg As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblRegModalTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegModalTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRegModalMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegModalMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnRegModalOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegModalOk As Global.System.Web.UI.WebControls.Button
End Class
